### ISSUE TITLE
Check we don't run out of gas for the oracle

### ISSUE THREAD

**Issue by vrde** [NeokingdomDAO/contracts#107]
@sirnicolaz I remember you mentioning an email notification in case the oracle doesn't update. Am I correct? Should we make it more visible?

Address of the oracle: https://escan.live/address/0x1899c0ae8a713490db086811d7738e96197dc6e4

**Comment by sirnicolaz** [comment]
At the current gas fee, the value inside the contract will allow it to run for another 975 days. I have set quarterly reminders on Discord to check the gas situation until 10th of January 2025. Plust a further reminder to add the new reminders for the following years, should the situation still be the same.
